language: c
sudo: false
script: make -f sys/unix/GNUmakefile install
notifications:
  irc:
    channels:
        - "chat.freenode.net#slashemextended"
        - "chat.freenode.net#em.slashem.me"
    on_success: always
    on_failure: always
    skip_join: true
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang
      osx_image: xcode8.0
